module.exports = {

  title: '澳門中原地產-移動A+',

  //判斷是否為生產環境
  isProduction: process.env.NODE_ENV === 'production',
  
  
  // 本地调试，测试账号
  DebugUser:{'UserKeyID':'77777777-7777-7777-7777-777777777777','StaffNo':'2016090007','UserName':'manager'
  ,'Mobile':'1334445589','DeptKeyID': 'B0D2C114-D0D5-4C9A-A4EC-4A6ECB1B6D10','DeptName':'系统管理组'
  ,'RoleKeyID':'34EE284F-5764-4C84-BB5D-A18984BE297C','RoleName': '电脑管理员'
    ,"PermisstionCodes": [
      "Property","Other.WorkStats_ALL","LianDong.LianDong","Customer.InquiryStatus.Modify-All",
      "Property.Key.Search-All","Customer.all-channel","Property.HistoryFollow.Search",
      "Property.DutyEmp.AddAndUpdate","Property.Follow.Top-All","Property.PreordainProperty.Search-All",
      "Property.FollowComment.Add","Property.DistrictRecommend.Other","Property.Status.ReserveTurnValid.ALL",
      "Property.Bank.Select","Property.Property.SearchLog-All","Customer.all-customer",
      "Estate.estate-manage","Property.Key.Return-All","Customer.taking",
      "Property.my-favorite","Customer.TurnPublicInquiry.Other","Center.log-manage",
      "DataCenter.WorkStats","System.employee","System.Role.Add","Customer.SalePrice.Modify-All",
      "Customer.PublicInquiryStatus.Modify-All","Customer.Inquiry.Search-All","Customer.Inquiry.PublicCount-All",
      "Customer","Customer.BlackList.Add","Customer.black-list",
      "Customer.Channel.Search-All",
      "Customer.TransactionType.Modify-All",
      "Customer.TakeSeeCount.Other",
      "Customer.TurnPublicInquiry.Turn-All",
      "Customer.ContactInformation.Modify-All",
      "Customer.public-channel",
      "Estate.Buildind.Delete",
      "Estate.Estate.Lock",
      "Customer.RentPrice.Modify-All",
      "System.User.Transfer.RealSurvey",
      "System.KeyBox",
      "System.User.Transfer.DutyEmp",
      "System.User.Edit.Vip",
      "System.org",
      "System.DeptData.Query",
      "System.User.Transfer.Trust",
      "System.Role.Delete",
      "System.User.Transfer.Key",
      "System.Dept.Delete",
      "System.Dept.Modify",
      "System.DeptData.Delete",
      "System.Dept.Add",
      "System.SystemSetting.Add-All",
      "System.DeptData.Add",
      "System.User.Transfer.Property",
      "Estate.NewProperty.NoLock",
      "System.User.Transfer.Performances",
      "System.User.Transfer",
      "Estate.Estate.Add",
      "Estate.House.Merge",
      "Estate.Estate.Turn",
      "Estate.Buildind.Set",
      "Estate.Buildind.Add",
      "Estate.estate-log",
      "Estate.Parameter.Set",
      "Estate",
      "Center",
      "Center.my-spread-sheets",
      "Property.RealSurvey.Delete-All",
      "Property.follow",
      "Property.ManagerIndex.Set-All",
      "Property.BasicInformation.Modify-All",
      "Customer.PublicInquiryToMyself.Other",
      "Customer.Inquiry.Delete-All",
      "Estate.Clean.Import",
      "Estate.House.Delete",
      "Estate.estate-recycle-bin",
      "Estate.Estate.Search-All",
      "Center.address-list",
      "Center.my-setting",
      "Center.spread-sheets",
      "Center.spread-sheets.Remove",
      "Center.Log.Search-All",
      "Center.my-spread-sheets-All",
      "Center.spread-sheets.Add",
      "Property.RealSurvey.Search-All",
      "Estate.Estate.Delete",
      "Advert",
      "Advert.manage-advert",
      "Advert.SendMacus",
      "Advert.Data-Statistics",
      "Center.system-message",
      "Center.spread-sheets.Update",
      "Center.my-message",
      "Center.CheckIn.Search-All",
      "Center.my-spread-sheets-print.edit",
      "Advert.NetWork.Search-All",
      "Advert.Centa-Network",
      "Advert.ManagerA.Search-All",
      "Advert.EditPrice",
      "Center.levelLog.All",
      "Property.TransactionInformation.Modify-All",
      "Property.Follow.Delete-All",
      "Property.OnlyTrust.Search-All",
      "Customer.Inquiry.Modify-All",
      "Property.Key.Add-All",
      "Property.FollowClean.Add",
      "Customer.Inquiry.SearchLog",
      "System.Dept.Search-All",
      "Customer.PublicInquiry.Delete-All",
      "Property.EditExpertDeal-All",
      "DataCenter.Ranking",
      "Property.my-dutyemp",
      "Property.TelephoneSecrecy.Edit",
      "Estate.House.Lock",
      "DataCenter.View.MyDept",
      "DataCenter",
      "Property.ReferralInformation.Search-All",
      "Property.public-estate",
      "Property.my-sharing",
      "Customer.take",
      "Property.Contribution.Search-All",
      "Property.TelephoneSecrecy.Add",
      "Property.Bank.GetData-All",
      "Property.HistoryOnlyTrust.Search",
      "Property.ContactInformation.Modify-All",
      "Property.RealSurvey.Modify-All",
      "Property.Key.Recover-All",
      "Property.Video.Select",
      "Property.ContactInformation.Search-All",
      "Property.Property.TogetherTakeSee",
      "Property.Property.Add",
      "Customer.public-customer",
      "Property.OnlyTrust.SearchFile-All",
      "Customer.inquiry-follow",
      "Customer.Referral-All",
      "System.log",
      "System.DeptData.Search",
      "Estate.Buildind.Transfer",
      "Property.RealSurvey.Search",
      "Property.EffectiveNum.Search-All",
      "Property.my-referral",
      "Property.FollowSupervise.Add",
      "Property.HistoryContactTel.Search",
      "Property.firstHand",
      "System",
      "System.role",
      "Customer.my-referral",
      "Customer.TurnOtherInquiry.Other",
      "Property.OnlyTrust.Restore",
      "Property.FollowNewContact.Add",
      "Property.FollowNewOpening.Add",
      "Property.Search-All",
      "Property.transactionReport",
      "Estate.Clean.Export",
      "Estate.House.Add",
      "Property.FollowCallPrice.Add",
      "Property.Status.ValidTurnOther.ALL",
      "Customer.Public.Search-All",
      "Property.HistoryPriceChange.Search",
      "Property.AllTrade.Search",
      "Property.PropertyStatus.Modify-All",
      "Property.FollowAgencyProcedures.Add",
      "Property.CallLog.Modify-All",
      "Property.war-zone",
      "Property.Follow.Search-All",
      "Property.PropertyCardInformation.Modify-All",
      "Customer.ContactInformation.Search-All",
      "Customer.ContactInformation.Add-All",
      "Property.EditTransaction-All",
      "Property.HistoryTakeSeeCount.Search",
      "Property.my-recommend",
      "Property.call-log",
      "Property.History.Search-All",
      "Property.Achievement.Search-All",
      "Property.ContactInformation.Add-All",
      "Property.TelephoneSecrecy.Export",
      "Property.phone-secrecy",
      "Customer.InquirySource.Modify-All",
      "Property.SecretRoom.Search",
      "Customer.Public.Search-All",
      "Estate.estate-param",
      "Estate.EstateFacilities.Modify",
      "Estate.House.Transfer",
      "Estate.House.Modify",
      "Estate.estate-clean",
      "Estate.EstateData.Import",
      "Estate.Buildind.Merge",
      "Estate.EstateBaseInfo.Modify",
      "Estate.Buildind.Modify",
      "Estate.EstatePhoto.Modify",
      "Property.Key.Modify-All",
      "Customer.HouseType.Modify-All",
      "Customer.Inquiry.Add-All",
      "Property.key",
      "Property.ReferralInformation.Modify-All",
      "Property.TelephoneSecrecy.Delete",
      "Property.OnlyTrust.Add-All",
      "Estate.Estate.Modify",
      "Property.call-price",
      "Property.OnlyTrust.Delete-All",
      "Property.OnlyTrust.Modify-All",
      "Customer.BlackList.Delete-All",
      "Estate.EstateDocument.Modify",
      "Property.DeleteExperDeal-All",
      "Property.area-manager-recommend",
      "Property.TurnPrivate.Modify-All",
      "Property.Key.ConfirmReceipt-All",
      "System.Dept.Set",
      "System.LevelOperation",
      "System.User.Add",
      "System.User.Transfer.Inquiry",
      "System.User.Delete",
      "System.system-settings",
      "System.User.Modify",
      "Property.Property.Modify-All",
      "Property.TurnPublic.Modify-All",
      "DataCenter.TakeSee",
      "Estate.EstateUpdateData.Import",
      "Property.RollBackTransaction-All",
      "Property.RealSurvey.Add-All",
      "System.User.Transfer.PropertyMyTurn",
      "Property.TogetherTakeSee.Search-All",
      "Property.FollowInformation.Add",
      "Property.Achievement-All",
      "Property.UnEffectiveNum.Search-All",
      "Property.Auditstatus.Set-All",
      "Property.Bank.Delete-All",
      "Property.RealPhoneNum.Search-All"
    ], // Token = 员工KeyID | 部门KeyID | 员工工号 | 所属A+公司KeyID | 所属A+城市KeyID | 角色KeyID
    "Token": "A2FC2F70-20E1-CFA7-7C5B-08D3F0C31277|AD757BE8-0886-CA9F-FE83-08D5A43679ED|2016090007|0A0EA5B4-571E-4B4A-B9AC-0157CBA85942|3F4374B7-35CA-473F-A471-CF34B8333211"},

  // 部署环境虚拟目录地址，本地则没有
  // baseURL: '/aplus_test/',

  /**
   * @type {boolean} true | false
   * @description Whether fix the header
   */
  fixedHeader: false,

  /**
   * @type {boolean} true | false
   * @description Whether need tagsView
   */
  tagsView: true,
  
  /**
   * @type {boolean} true | false
   * @description Whether show the logo in sidebar
   */
  sidebarLogo: true
}
